/* IMPORTANT: keep in sync with hourly_asn ib db_schema_clickhouse.sql */
/* Used *only* in NetworkInterface::aggregateASNModeFlows() */
CREATE TABLE `hourly_asn` (
/*`ID` INTEGER PRIMARY KEY AUTOINCREMENT, */
/*`NTOPNG_INSTANCE_NAME` TEXT, */
`INTERFACE_ID` INTEGER NOT NULL,
`IP_PROTOCOL_VERSION` INTEGER NOT NULL,
`FIRST_SEEN` DATETIME NOT NULL,
`LAST_SEEN` DATETIME NOT NULL,
`SRC2DST_BYTES` INTEGER NOT NULL,
`DST2SRC_BYTES` INTEGER NOT NULL,
`TOTAL_BYTES` INTEGER NOT NULL,
`SRC2DST_PACKETS` INTEGER NOT NULL,
`DST2SRC_PACKETS` INTEGER NOT NULL,
`SRC_ASN` INTEGER NOT NULL,
`DST_ASN` INTEGER NOT NULL,
`SRC_PEER_ASN` INTEGER NOT NULL,
`DST_PEER_ASN` INTEGER NOT NULL,
`PROBE_IP` TEXT NOT NULL, /* EXPORTER_IPV4/V6_ADDRESS */
`INPUT_SNMP` INTEGER NOT NULL,
`OUTPUT_SNMP` INTEGER NOT NULL,
`SRC_SITE_ID` INTEGER NOT NULL,
`DST_SITE_ID` INTEGER NOT NULL
);
